#!/usr/bin/env bash
set -e

BIN="${HOME}/bin"
VERSION="1.31.0"

URL="https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-$(uname -s)-$(uname -m)"

echo "download from ${URL}"

mkdir -p ${BIN}
wget -nv ${URL} -O "${BIN}/buf"

chmod +x "${BIN}/buf"
