#!/usr/bin/env bash
set -e

BLACK_ARG="--check"
RUFF_ARG=""
CODE="onyx_otc tests examples"

if [ "$1" = "fix" ] ; then
    BLACK_ARG=""
    RUFF_ARG="--fix"
fi

echo "run black"
black ${CODE} ${BLACK_ARG}
echo "run ruff"
ruff check ${CODE} ${RUFF_ARG}
echo "run mypy"
mypy ${CODE}
