#!/usr/bin/env bash
set -e

BLACK_ARG="--check"
RUFF_ARG=""

if [ "$1" = "fix" ] ; then
    BLACK_ARG=""
    RUFF_ARG="--fix"
fi

echo "run black"
black onyx_otc tests ${BLACK_ARG}
echo "run ruff"
ruff check onyx_otc tests ${RUFF_ARG}
echo "run mypy"
mypy onyx_otc tests
