# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: otc/v1/responses.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from otc.v1 import common_pb2 as otc_dot_v1_dot_common__pb2
from otc.v1 import types_pb2 as otc_dot_v1_dot_types__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16otc/v1/responses.proto\x12\x06otc.v1\x1a\x13otc/v1/common.proto\x1a\x12otc/v1/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd1\x04\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63lient_order_id\x18\x02 \x01(\t\x12\x12\n\naccount_id\x18\x03 \x01(\t\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12:\n\x16last_updated_timestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12!\n\x08quantity\x18\x0b \x01(\x0b\x32\x0f.otc.v1.Decimal\x12\x1a\n\x04side\x18\x0c \x01(\x0e\x32\x0c.otc.v1.Side\x12%\n\norder_type\x18\r \x01(\x0e\x32\x11.otc.v1.OrderType\x12#\n\x05price\x18\x0f \x01(\x0b\x32\x0f.otc.v1.DecimalH\x00\x88\x01\x01\x12(\n\nstop_price\x18\x15 \x01(\x0b\x32\x0f.otc.v1.DecimalH\x01\x88\x01\x01\x12.\n\x10\x64isplay_quantity\x18\x16 \x01(\x0b\x32\x0f.otc.v1.DecimalH\x02\x88\x01\x01\x12\x34\n\rtime_in_force\x18\x17 \x01(\x0e\x32\x18.otc.v1.OrderTimeInForceH\x03\x88\x01\x01\x12\x33\n\nexpiration\x18\x18 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x04\x88\x01\x01\x12\x13\n\x06manual\x18\x19 \x01(\x08H\x05\x88\x01\x01\x42\x08\n\x06_priceB\r\n\x0b_stop_priceB\x13\n\x11_display_quantityB\x10\n\x0e_time_in_forceB\r\n\x0b_expirationB\t\n\x07_manual\"l\n\x0cSubscription\x12 \n\x07\x63hannel\x18\x01 \x01(\x0e\x32\x0f.otc.v1.Channel\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12*\n\x06status\x18\x04 \x01(\x0e\x32\x1a.otc.v1.SubscriptionStatus\"?\n\x08OtcError\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\"\n\x04\x63ode\x18\x02 \x01(\x0e\x32\x14.otc.v1.OtcErrorCode\"\xd2\x01\n\x0bOtcResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1e\n\x05order\x18\x0b \x01(\x0b\x32\r.otc.v1.OrderH\x00\x12,\n\x0csubscription\x18\x0c \x01(\x0b\x32\x14.otc.v1.SubscriptionH\x00\x12$\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x10.otc.v1.OtcErrorH\x01\x88\x01\x01\x42\n\n\x08responseB\x08\n\x06_errorB\x0b\xaa\x02\x08Onyx.Otcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'otc.v1.responses_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\010Onyx.Otc'
  _globals['_ORDER']._serialized_start=109
  _globals['_ORDER']._serialized_end=702
  _globals['_SUBSCRIPTION']._serialized_start=704
  _globals['_SUBSCRIPTION']._serialized_end=812
  _globals['_OTCERROR']._serialized_start=814
  _globals['_OTCERROR']._serialized_end=877
  _globals['_OTCRESPONSE']._serialized_start=880
  _globals['_OTCRESPONSE']._serialized_end=1090
# @@protoc_insertion_point(module_scope)
