name: build

on:
  push:
    branches-ignore:
      - deploy
    tags-ignore:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    environment: uat
    env:
      PYTHON_ENV: ci
      ONYX_WS_V1_URL: ${{ vars.ONYX_WS_V1_URL }}
      ONYX_WS_V2_URL: ${{ vars.ONYX_WS_V2_URL }}
      ONYX_API_TOKEN: ${{ secrets.ONYX_API_TOKEN }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install buf
        run: make install-buf
      - name: Install poetry
        run: pip install -U pip poetry
      - name: Install dependencies
        run: make install
      - name: lint protobuf definitions
        run: make lint-proto
      - name: run compile-protos
        run: make compile-protos
      - name: lint python code
        run: make lint-py-check
      - name: run tests
        run: make test

  publish:
    name: publish to pypi
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
    needs:
      - build
    env:
      PYTHON_ENV: ci
    if: ${{ github.ref == 'refs/heads/main' && github.event.head_commit.message == 'release' }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install poetry
        run: pip install -U pip poetry
      - name: Install dependencies
        run: make install
      - name: run compile-protos
        run: make compile-protos
      - name: build
        run: poetry build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
