name: build

on:
  push:
    branches-ignore:
      - deploy
    tags-ignore:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHON_ENV: ci
      ONYX_WS_V1_URL: wss://ws.uat.onyxhub.co/stream/v1
      ONYX_WS_V2_URL: wss://ws.uat.onyxhub.co/stream/v2
      ONYX_API_TOKEN: ${{ secrets.ONYX_API_TOKEN }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install buf
        run: make install-buf
      - name: Install poetry
        run: pip install -U pip poetry
      - name: Install dependencies
        run: make install
      - name: lint protobuf definitions
        run: make lint
      - name: run compile-protos
        run: make compile-protos
      - name: lint python code
        run: make lint-py-check
      - name: run tests
        run: make test
